OFM-Check: Collect Producer Warnings and Errors
Same as in OAM-Check

diff --git a/.github/workflows/openknx-ofm-check.yml b/.github/workflows/openknx-ofm-check.yml
--- a/.github/workflows/openknx-ofm-check.yml
+++ b/.github/workflows/openknx-ofm-check.yml
@@ -104,7 +104,21 @@ jobs:
       - name: Create knxprod (Precheck to fail fast before pio-setup)
         run: |
           cd ${{ inputs.oam }}
-          OpenKNXproducer create --Debug -h include/knxprod.h src/${{inputs.KNXPROD_PREFIX}}${{ inputs.target != '' && format('-{0}', inputs.target) || '' }}
+          OpenKNXproducer create --Debug -h include/knxprod.h src/${{inputs.KNXPROD_PREFIX}}${{ inputs.target != '' && format('-{0}', inputs.target) || '' }} 2>&1 | tee producer.log
+          exit_code=${PIPESTATUS[0]}
+          if [ $exit_code -ne 0 ]; then
+            # Collect all outputs starting with "-->"
+            error_lines=$(grep -E '^\s*(-->|Unhandled exception\.)' producer.log | grep -Ev -- '--> Skipping creation of src/[^ \.]+\.knxprod due to check errors! <--' | tr '\n' ' // ')
+            if [ -n "$error_lines" ]; then
+              echo "::error:: $error_lines"
+            fi
+            exit $exit_code
+          fi
+
+          warn_lines=$(grep -E '^\s*-->\s*WARN' producer.log | tr '\n' ' // ')
+          if [ -n "$warn_lines" ]; then
+            echo "::warning:: $warn_lines"
+          fi
 
       - name: Install Python
         uses: actions/setup-python@v6
